Uploading a sample
Azure-Samples/azure-docs-powershell-samples pull request #6
Opened 2023-11-20 23:43 UTC by normesta

## Purpose
Sample contributed by the CSS team. It's been super well tested. I'm a writer on the Azure Storage team and intend to source this code in an article.
* ...

## Does this introduce a breaking change?

```
[ ] Yes
[X ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[X ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
Log into Azure by using the "Connect-AzAccount". Add the name of a storage account and a resource group to the script and then run the script at a Windows PowerShell window.

2023-11-21 16:43 UTC, normesta commented
@mikefrobbins are you the appropriate person to review this sample / merge? I don't seem to have merge power in this repo.

Thx!

Norm E.

2023-11-27 19:17 UTC, mikefrobbins commented
@normesta I'm the correct contact. I'm reviewing the sample now. Is it used in our documentation somewhere?

2023-11-27 19:25 UTC, normesta commented
Thanks @mikefrobbins. RE: docs, yes, it will be used in an article in docs. Thx!

2023-11-27 22:50 UTC, mikefrobbins requested changes
No logic changes since it's well tested, but several best practice, formatting, and usability changes requested.

2023-11-27 22:50 UTC, mikefrobbins commented on storage/calculate-container-size/calculate-container-sizes-in-account.ps1
> +$resource_group = "<name-of-your-resource-group"
```suggestion
<#
.SYNOPSIS
Calculates the total size of blobs in all containers in a specified Azure storage account.

.DESCRIPTION
Before running this script, ensure you have:
- A storage account created
- At least one container in the storage account
- Uploaded some blobs into the container

.EXAMPLE
.\Get-AzureStorageAccountBlobSize.ps1 -StorageAccountName mystorageaccount -ResourceGroupName myResourceGroup

.NOTES
This script incurs transactional costs for Azure requests.
#>

[CmdletBinding()]
param (
    [ValidateNotNullOrEmpty()]
    [string]$ResourceGroupName = '<name-of-your-resource-group>',
    
    [ValidateNotNullOrEmpty()]
    [string]$StorageAccountName = '<name-of-your-storage-account>'
)

$containerstats = @()
```

Use comment-based help and parameterize the script. Without `[CmdletBinding()]`, the `Write-Verbose` statements will never be displayed due to the script not having a **Verbose** parameter.

2023-11-27 22:50 UTC, mikefrobbins commented on storage/calculate-container-size/calculate-container-sizes-in-account.ps1
> +      }
```suggestion
      $containerstats += [PSCustomObject] @{ 
        Name = $container 
        TotalBlobCount = $total_blob_count 
        TotalBlobUsageinGB = $total_usage/1GB
        SoftDeletedBlobCount = $soft_delete_count
        SoftDeletedBlobUsageinGB = $soft_delete_usage/1GB
	SnapshotCount = $snapshot_count
	SnapshotUsageinGB = $snapshot_usage/1GB
	VersionCount = $version_count
	VersionUsageinGB = $version_usage/1GB
      }
```
Format the code with the same alignment.

2023-11-27 22:50 UTC, mikefrobbins commented on storage/calculate-container-size/calculate-container-sizes-in-account.ps1
> +  {
```suggestion
  if ($containers -ne $null) {
```
Use OTBS (One true brace style) so your `if` statements are formatted the same as the code for the `do` loops.

2023-11-27 22:50 UTC, mikefrobbins commented on storage/calculate-container-size/calculate-container-sizes-in-account.ps1
> +    {
```suggestion
    for ([int] $c = 0; $c -lt $containers.Count; $c++) {
```

2023-11-27 22:50 UTC, mikefrobbins commented on storage/calculate-container-size/calculate-container-sizes-in-account.ps1
> +        {
```suggestion
        if ($blobs -ne $null) {
```

2023-11-27 22:50 UTC, mikefrobbins commented on storage/calculate-container-size/calculate-container-sizes-in-account.ps1
> +          {
```suggestion
          for ([int] $b = 0; $b -lt $blobs.Count; $b++) {
```

2023-11-27 22:50 UTC, mikefrobbins commented on storage/calculate-container-size/calculate-container-sizes-in-account.ps1
> +            {
```suggestion
            if ($blobs[$b].IsDeleted) {
```

2023-11-27 22:50 UTC, mikefrobbins commented on storage/calculate-container-size/calculate-container-sizes-in-account.ps1
> +            {
```suggestion
            if ($blobs[$b].SnapshotTime -ne $null) {
```

2023-11-27 22:50 UTC, mikefrobbins commented on storage/calculate-container-size/calculate-container-sizes-in-account.ps1
> +            {
```suggestion
            if ($blobs[$b].VersionId -ne $null) {
```

2023-11-27 22:50 UTC, mikefrobbins commented on storage/calculate-container-size/calculate-container-sizes-in-account.ps1
> +          {
```suggestion
          if ($blob_continuation_token -ne $null) {
```
Use consistent casing.

2023-11-27 22:50 UTC, mikefrobbins commented on storage/calculate-container-size/calculate-container-sizes-in-account.ps1
> +  {
```suggestion
  if ($container_continuation_token -ne $null) {
```

2023-11-27 22:50 UTC, mikefrobbins commented on storage/calculate-container-size/calculate-container-sizes-in-account.ps1
> +      $blob_continuation_token = $null
```suggestion
      $soft_delete_count = 0
      $version_usage = 0
      $version_count = 
      $snapshot_count = 0 
      $snapshot_usage = 0
      $blob_continuation_token = $null
```
Format the code with proper alignment.

2023-11-28 00:08 UTC, normesta commented
Thank you @mikefrobbins! I committed your suggestions and tested the updates and all works great.

2023-11-28 17:51 UTC, mikefrobbins approved these changes
LGTM

2023-11-28 17:52 UTC, merged